[workspace]
members = [
  "stream",
  "hash",
  "endpoint",
  "protocol",
  "agent",
  "net",
  "discovery",
  "context",
  "log",
  "metrics",
  "ds",
  "tests",
]


[profile.release]
#opt-level = 3
#debug=true
#codegen-units = 1
#lto = "fat"
