[package]
name = "protocol"
version = "0.1.0"
authors = ["icy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
net = { path = "../net" }
hash = { path = "../hash" }
ds = { path = "../ds" }
log = { path = "../log" }

enum_dispatch = "*"
async-trait = "*"
byteorder = "*"
futures = "*"
bytes = "*"
rand = "*"

