[package]
name = "stream"
version = "0.1.0"
authors = ["icycrystal4"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-deque = "*"
crossbeam-utils = "*"
crossbeam-channel = "*"
futures = "*"
tokio = { version = "*", features = ["full"]}
protocol = { path = "../protocol" }
hash = { path = "../hash" }
ds = { path = "../ds" }
rand = "*"
lockfree = "*"
tokio-util = "*"
spin = { version = "0.9.0"}
enum_dispatch = "*"
bytes = "*"
cache_line_size = "*"
