[package]
name = "agent"
version = "0.1.0"
authors = ["icy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
context = { path = "../context" }
net = { path = "../net"}
protocol = { path = "../protocol" }
endpoint = { path = "../endpoint" }
discovery = { path = "../discovery" }
log = { path = "../log" }
stream = { path = "../stream" }
metrics = { path = "../metrics" }

tokio = {version = "1.9.0", features = ["rt", "net", "rt-multi-thread", "time", "macros"]}
